### ISSUE TITLE
Sortierfunktion bei Kandidaten und Backlinks funktioniert nicht

### ISSUE THREAD

**Issue by poolie** [pooliestudios/linkmotor#2]
Die Sortierfunktion bei Kandidaten und Backlinks funktioniert nicht. Alle Links (?sort= ...) scheinen richtig, aber nichts passiert.

**Comment by dolbertz** [comment]
Den Fehler kann ich schon mal bestätigen, auch wenn ich die Ursache noch nicht herausgefunden habe. Die Komponente, die dafür zuständig ist, hängt die Sortieroptionen einfach nicht an die Datenbankanfrage an. Wenn alle Stricke reißen, werde ich das dann manuell nachbauen.

**Comment by dolbertz** [comment]
Das ist nun mit v1.5.4 behoben.
