### ISSUE TITLE
Error bei manuellem Anstoß des crawls

### ISSUE THREAD

**Issue by gorbo** [pooliestudios/linkmotor#3]
Ich habe meine Links vorher importiert. Wenn die Linkliste aufrufe, einen einzelnen Link wähle und bei der Crawlhistorie einen manuellen crawl anstoße, kommt folgende Fehlermeldung:

Fatal error: Call to undefined method Pool\LinkmotorBundle\Entity\User::iIsInactive() in /www/htdocs/linkmotor/src/Pool/LinkmotorBundle/Entity/NotificationSettingRepository.php on line 145

Ich habe es noch nciht absolut nachvollziehen können, aber bei einem Link hatte ich beim import angegegeben er sei nofollow. Bei manuellem crawl ist der Fehler aufgetreten. Anschließend habe ich den Status geändert, nochmal den crawl angestoßen und es ging.

Bei einem anderen Link leider nicht.

**Comment by dolbertz** [comment]
Das sollte mit dem Release v1.5.3 behoben sein: https://github.com/pooliestudios/linkmotor/releases/tag/v1.5.3

Bitte die Anleitung zum Update beachten: https://github.com/pooliestudios/linkmotor/blob/master/UPDATES.md
