### ISSUE TITLE
Error nach update

### ISSUE THREAD

**Issue by gorbo** [pooliestudios/linkmotor#4]
Hallo,
habe soeben von der v1.5.2 auf die v1.5.6 nach Vorgabe geupdatet. Ergebnis bei jetzigen Aufruf der Seite:

Fatal error: Class Proxies\__CG__\Pool\LinkmotorBundle\Entity\Project contains 6 abstract methods and must therefore be declared abstract or implement the remaining methods (Doctrine\Common\Proxy\Proxy::__setInitialized, Doctrine\Common\Proxy\Proxy::__setInitializer, Doctrine\Common\Proxy\Proxy::__getInitializer, ...) in /linkmotor/app/cache/prod/doctrine/orm/Proxies/__CG__PoolLinkmotorBundleEntityProject.php on line 298

Und nun?

**Comment by dolbertz** [comment]
Das sieht für mich aus, als ob der Cache nicht gelöscht wurde. Nach dieser Anleitung hier
  https://github.com/pooliestudios/linkmotor/blob/master/UPDATES.md
sollte das automatisch im Schritt "php composer.phar install" passieren.

Du kannst alle 5 Schritte ruhig noch einmal ausführen. Kannst Du dann die Ausgabe hier mit als Kommentar angeben? Oder vielleicht besser an dirk@pooliestudios.com schicken, damit keine Pfadinformationen, etc. für andere hier sichtbar sind.

**Comment by dolbertz** [comment]
Vielen Dank für die E-Mail! Du musst noch als sechsten Punkt (also nach "app/console assetic:dump --env=prod") diese Zeile ausführen:
  app/console cache:clear --env=prod

Während des composer install-Aufrufs wird nur der Cache der Entwicklungsumgebung (--env=dev) gelöscht. Sorry! Lasse mich bitte wissen, ob das das Problem beseitigt. Dann kann ich auch noch die Update-Anleitung anpassen.

**Comment by gorbo** [comment]
Läuft bei mir :) Vielen Dank!

**Comment by dolbertz** [comment]
Super! Die Update-Anleitung habe ich nun auch angepasst. Danke!
