### ISSUE TITLE
Passende nginx config

### ISSUE THREAD

**Issue by PatrickHuetter** [pooliestudios/linkmotor#5]
Hi zusammen,

könntet ihr noch eine passende nginx config bereitstellen?
Wäre sicherlich super für die Personen, die nginx, statt Apache einsetzen.

Viele Grüße

**Comment by b3nelof0n** [comment]
http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html

**Comment by PatrickHuetter** [comment]
Danke @b3nelof0n, die default nginx config für symfony hat funktioniert.
