### ISSUE TITLE
Problem mit Linkmotor SEO Services

### ISSUE THREAD

**Issue by PatrickHuetter** [pooliestudios/linkmotor#6]
Nachdem ich Linkmotor auf meinem Server installiert habe, kann ich es nicht nutzen, da der Einrichtungsassistent mich zwingt die Zugangsdaten für die SEO Services einzutragen. Ich würde gerne neue Zugangsdaten anfordern, da ich noch keine habe, aber auch dies funktioniert nicht.

![bildschirmfoto 2016-01-27 um 22 15 22](https://cloud.githubusercontent.com/assets/1142911/12628641/6f4cd67c-c544-11e5-96f8-74d953a87a6a.png)

Laut prod.log scheint es ein Problem mit dem internen Routing zu geben. Ich vermute das könnte mit nginx zusammen hängen, da ich die default nginx config von #5 benutzt habe. Gibt es eine Referenz Konfiguration für Linkmotor in Kombination mit NGINX? Oder kennt jemand die Lösung für das Problem?

```
[2016-01-27 22:30:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /services/accounts/register/self-hosted/"" at /var/www/linkmotor/app/cache/prod/classes.php line 1885 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /services/accounts/register/self-hosted/\" at /var/www/linkmotor/app/cache/prod/classes.php:1885, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at /var/www/linkmotor/app/cache/prod/appProdUrlMatcher.php:1400)"} []
```

**Comment by dolbertz** [comment]
Kann es sein, dass Du in der app/config/parameters.yml die folgende Zeile nicht drinstehen hast, bzw. den Wert auf der rechten Seite des Doppelpunktes entfernt hast?
seoservices.url: https://linkmotor.de/services

Denn die URL /services/accounts/register/self-hosted/ soll nämlich eigentlich genau dort aufgerufen werden und nicht auf Deinem lokalen Server/Rechner.

Nach dem Anpassen der parameters.yml musst Du noch einmal app/console cache:clear --env=prod aufrufen.

Einen Zusammenhang mit nginx statt Apache kann ich gerade nicht erkennen, ich habe nginx aber auch nur mal probeweise in einem anderen Projekt eingesetzt. Ich kann mich da also täuschen, wüsste dafür dann aber gerade auch keine Lösung.

**Comment by PatrickHuetter** [comment]
Danke @dolbertz, ich hatte in der Tat die seoservices url erstmal verändert gehabt und anschließend wieder korrigiert. Wusste nicht das dies gecached wird. ```app/console cache:clear --env=prod ``` hat abhilfe geschaffen und nun läuft es! :+1:
